name: Build and Deploy

on:
  push:
    branches: [ pixi ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare environment
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - run: npm install --global pnpm

      - name: Install deps
        run: pnpm i
        
      - name: Build website
        run: pnpm run build
        
      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist